---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-1.26
  labels:
    app: nginx
    version: "1.26"
spec:
  minReadySeconds: 1
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      version: "1.26"
  template:
    metadata:
      name: nginx-1.26
      labels:
        app: nginx
        version: "1.26"
    spec:
      containers:
        - name: nginx
          image: nginx:1.26
          ports:
            - containerPort: 80