---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  ports:
    - name: nginx-svc
      port: 80
      targetPort: 80
  selector:
    app: nginx
    version: "1.26"
  type: LoadBalancer