---
apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  labels:
    app: httpd
spec:
  ports:
    - name: httpd-svc
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: httpd
  type: LoadBalancer

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
  labels:
    app: httpd
spec:
  minReadySeconds: 1
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      name: httpd-pod
      labels:
        app: httpd
        version: "2.4"
    spec:
      containers:
        - name: httpd
          image: httpd:2.4
          ports:
            - containerPort: 80
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 1
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /
              port: 80
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: 1
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /
              port: 80