---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-config-file
spec:
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - 1d
      volumeMounts:
        - name: dummy-files
          mountPath: /tmp/dummy
  volumes:
    - name: dummy-files
      configMap:
        name: dummy-cm
        optional: false