---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: nginx-lb
      port: 80 #Exposed Port (Host Port)
      targetPort: 80 #Container Port
      protocol: TCP