---
apiVersion: v1
kind: Pod
metadata:
  name: docker-private-image-pod
spec:
  containers:
    - name: private-image-pod
      image: nagasuribabukola/bankapp:latest
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: docker-login-secret