---
apiVersion: v1
kind: Secret
metadata:
  name: docker-login-secret
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImJtRm5ZWE4xY21saVlXSjFhMjlzWVRwVGRYSmxjMmhBTXpZNU53PT0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9
type: kubernetes.io/dockerconfigjson