---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  MYSQL_ROOT_PASSWORD: Um9vdFJvb3Q=
  MYSQL_USER: RGV2T3BzQWRtaW4=
  MYSQL_PASSWORD: U3VyZXNoQDM2OTc=
  MYSQL_DATABASE: RGV2T3BzRGF0YQ==