---
apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  backoffLimit: 5
  template:
    metadata:
      name: job-alpine
    spec:
      restartPolicy: OnFailure
      containers:
        - name: alpine
          image: alpine:latest
          args:
            - sleep
            - 10s