---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - name: nginx-svc
      port: 8080 # The service's port (internal cluster communication)
      targetPort: 80 # The container's port where the application is running
      protocol: TCP