---
apiVersion: v1
kind: Pod
metadata:
  name: initcontainers-demo
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      ports:
        - containerPort: 80
  initContainers:
    - name: alpine
      image: alpine:3
      args:
        - "sleep" 
        - "30"
    - name: alpine-2
      image: alpine:3
      args:
        - "sleep" 
        - "15"