---
apiVersion: v1
kind: Pod
metadata:
  name: restart-onfailure-failure
spec:
  restartPolicy: OnFailure
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - 3SM

---
apiVersion: v1
kind: Pod
metadata:
  name: restart-onfailure-success
spec:
  restartPolicy: OnFailure
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - 3s