---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    app: jenkins
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: purpose
              operator: In
              values:
                - stage
  containers:
    - name: jenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080