---
apiVersion: v1
kind: Pod
metadata:
  name: exercise-3
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: alpine-1
      image: alpine:3
      args:
        - sleep
        - 1d
    - name: alpine-2
      image: alpine:3
      args:
        - sleep
        - 10s