---
apiVersion: v1
kind: Pod
metadata:
  name: exercise-2
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: alpine
      image: alpine:3
      args:
        - sleep
        - 1d