---
apiVersion: v1
kind: Pod
metadata:
  name: exercise-4
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: httpd
      image: httpd:2
      ports:
        - containerPort: 80