---
apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - 1d
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80