---
apiVersion: v1
kind: ReplicationController
metadata:
  name: alpine-rc
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    app: alpine
  template:
    metadata:
      name: alpine-pod
      labels:
        app: alpine
    spec:
      containers:
        - name: alpine
          image: alpine:3
          args:
            - sleep
            - 1d